### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by msmichellegar** [proseccojs/proseccojs#20]
![screen shot 2015-09-02 at 2 57 28 pm](https://cloud.githubusercontent.com/assets/10683087/9631684/fc005818-5182-11e5-8904-249e51a6f472.png)

CC: @wallcrawler

**Comment by claireinez** [comment]
Seems to be working for me!

**Comment by msmichellegar** [comment]
Ah, maybe just a dodgy Brugge wifi thing then. Will try on some different devices.

**Comment by msmichellegar** [comment]
Confirmed: dodgy wifi issue.
