### ISSUE TITLE
Console.logs

### ISSUE THREAD

**Issue by claireinez** [proseccojs/proseccojs#9]
We should probably remove console.logs before pushing to heroku.

Or we could add a sort of easter egg log for the truly dedicated devs!

**Comment by ronanyeah** [comment]
link to the lines

**Comment by claireinez** [comment]
Oh gosh, I apologise for my poor issue etiquette! All are in index.js:
- https://github.com/proseccojs/proseccojs/blob/master/public/index.js#L3
- https://github.com/proseccojs/proseccojs/blob/master/public/index.js#L5
- https://github.com/proseccojs/proseccojs/blob/master/public/index.js#L7
